### ISSUE TITLE
Undefined local variable or method `pickup_extra_info'

### ISSUE THREAD

**Issue by frmichel** [farend/scm-creator#9] opened 2018-09-28 15:11 UTC
Hi,

I'm not sure if the project is still maintained or not. I'm trying to use the plugin with Redmine 3.4.6 on a CentOS 7.5. Is the plugin supposed to be compatible with this Redmine version?

My redmine is up and running, integrated with Git and Svn. I've installed the plugin and called  "rake redmine:plugins:migrate RAILS_ENV=production".

Any time I click on the "Create new repository" button in a project's Settings > Repositories > New repository form, I get an error in the production.log:

```
NameError (undefined local variable or method `pickup_extra_info' for #<RepositoriesController:0x00007f870db08e48>):
  plugins/redmine_scm/lib/scm_repositories_controller_patch.rb:50:in `create_with_scm'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Any idea what goes wrong?

Thx in advance,
   Franck.

**Comment by ishikawa999** [comment] 2018-10-01 06:57
Thank you for trying to use this plugin.

I merged the code to solve the problem you reported to the master branch.
Could you please try the "rake redmine: plugins: migrate RAILS_ENV = production" once again after getting the latest code?

**Comment by frmichel** [comment] 2018-10-01 07:57
Dear @ishikawa999, thank you for your response. I've pulled the new code and rerun  the commands (the bundle command was necessary to get octokit):
```
bundle install --without development test
rake redmine:plugins:migrate RAILS_ENV=production
```

I now have a different error when trying to create a repo. Note the error is the same for svn and git.
```
WARNING: Can't mass-assign protected attributes for Repository::Git: id, root_url, type
        plugins/redmine_scm/lib/scm_repositories_controller_patch.rb:44:in `create_with_scm'
        lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  ^[[1m^[[36mRepository Exists (0.6ms)^[[0m  ^[[1mSELECT  1 AS one FROM `repositories` WHERE (`repositories`.`identifier` = BINARY '' AND `repositories`.`project_id` = 8) LIMIT 1^[[0m
Creating reporitory: /var/lib/git/testgit.git
cannot find/execute: /usr/local/bin/pre-create.sh
Repository creation failed
```

Since I have no script /usr/local/bin/pre-create.sh (nor post-create and pre/post-delete) I've simply removed them from the scm.yml, and restarted. Still, the error seems to be the same:

```
WARNING: Can't mass-assign protected attributes for Repository::Git: id, root_url, type
        plugins/redmine_scm/lib/scm_repositories_controller_patch.rb:44:in `create_with_scm'
        lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  ^[[1m^[[35mRepository Exists (0.6ms)^[[0m  SELECT  1 AS one FROM `repositories` WHERE (`repositories`.`identifier` = BINARY '' AND `repositories`.`project_id` = 8) LIMIT 1
Creating reporitory: /var/lib/git/testgit.git
Repository creation failed
```

Are the pre/post-create/delete required or optional? Did I do right hen I removed the properties?

Any other idea?

Thanks,
   Franck.

**Comment by ishikawa999** [comment] 2018-10-01 10:59
Thank you for trying quickly.
And thank you for sharing the error.

"can not find / execute: /usr/local/bin/pre-create.sh" seems not to be a cause of repository creation failure.

I think there is a possibility that it may be caused by an error in the permissions of /var/lib/git or setting of scm.yml.
Unfortunately the current scm-creator can not confirm the cause of specific repository creation failure. 
The plugin user has to investigate why repository creation fails.

I have two ideas to solve the problem.
* Please check whether the permissions of the  directory you created is correct.
(https://github.com/farend/scm-creator#1-creating-root-directory)
* Could you please share the settings of scm.yml?(There is no need to share important information.)
  There may be something I can advise you.

I hope you will go well.

**Comment by ishikawa999** [comment] 2018-11-07 07:03
Since the problem of "Undefined local variable or method `pickup_extra_info'" seems to be solved, I will close this issue.
If there is progress on https://github.com/farend/scm-creator/issues/9#issuecomment-425819937, please make a new issue.

Thanks.

**Closed as completed** 2018-11-07 07:05 UTC

**Comment by frmichel** [comment] 2018-11-07 08:25
Dear @ishikawa999, thank you for your response and sorry for not getting back to you earlier. Actually I had not seen your response yet. I'm not able to try that right now but as soon as I do I will let you know.
Regards,
    Franck.
